### ISSUE TITLE
Unnecessary navigation class

### ISSUE THREAD

**Issue by jim-rosales** [Sfmahmoudi/TeaCozy#4]
You don't need to use a class to apply this rule. Since the rule is only being applied to the nav element, you can use its tag. 

For example:
```CSS
nav {
  display: flex;
  justify-content: flex-end;
  align-items: center;
}
```
https://github.com/Sfmahmoudi/TeaCozy/blob/d2196f5e1f5de0917d759eb5060b6a67c8a1410d/resources/css/style.css#L40-L44
