### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by jim-rosales** [Sfmahmoudi/TeaCozy#5]
Another way you could have applied this rule is to do the following:
```CSS
.varieties span {
  display: flex;
  flex-direction: column;
}
```
By using this method you can forgo using a class for each span. 

https://github.com/Sfmahmoudi/TeaCozy/blob/d2196f5e1f5de0917d759eb5060b6a67c8a1410d/resources/css/style.css#L99-L102
